### ISSUE TITLE
Why yet another nix?

### ISSUE THREAD

**Issue by dumblob** [maxmcd/bramble#44]
I wonder what are the (dis)advantages of Bramble compared to nix (which is itself mentioned in the readme but not elaborated).

**Comment by maxmcd** [comment]
Totally a fair question. Best place to get an understanding might be this comment thread: https://lobste.rs/s/g1tqfe/bramble_purely_functional_build_system

Happy to clarify anything in that thread, or happy to provide more info if that's insufficient.

**Comment by dumblob** [comment]
Ah, thanks. I think I understand now.

It seems boiling a lot due to lots of new ideas, approaches (e.g. Skylark as nix frontend sparked my interest), new contacts, similar projects (both known and unknown ones), etc. So I'll rather wait a few weeks/months before it settles down :wink:.

Btw. if you decided to also take a stab at packaging (not only a build system), feel free to get in touch with devs of @chimera-linux as they started quite recently developing their "build system" with some similarities (as well as dissimilarities) to Bramble. (disclaimer: I know the lead dev - an extremely experienced & capable person).

**Comment by dumblob** [comment]
Btw. I always liked the way Ekam build system handles projects - see https://github.com/capnproto/ekam . Maybe another tiny source of inspiration for certain things.

**Comment by dumblob** [comment]
Actually one more question - would be Bramble suitable for new projects to completely get rid of Makefiles, cmake, premake, and many other rather *generic* build systems (note pip, ... are not generic build/pkg_mgmt systems)?

**Comment by maxmcd** [comment]
Yes, I think so, but not at the moment, needs quite a bit more work.
