### ISSUE TITLE
Enable discussions?

### ISSUE THREAD

**Issue by jedahan** [maxmcd/bramble#52]
I would like to start an open-ended discussion about one of the difficulties I see with 'in-the-wild' nix configurations, so folks can share their thoughts and experiences without necessarily 'solutioning an issue'. If you see issues as reasonable for open-ended discussion, I'll close this and open a new one with the specific concerns I have in mind.

**Comment by maxmcd** [comment]
Great idea, enabled!

**Comment by maxmcd** [comment]
Also thanks for bringing this discussion (lol). Looking forward to chatting through the details.
